name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.9.0
    with:
      env: '["py310", "py311", "py312", "py313", "py314"]'
